# Generated by Django 3.1.7 on 2021-04-03 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CowSayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowsay_type', models.CharField(choices=[('Default', 'Default'), ('Tux', 'Tux'), ('Dragon', 'Dragon'), ('Hello_Kitty', 'Hello_Kitty'), ('Skeleton', 'Skeleton')], default='Default', max_length=15)),
                ('text_line', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
