# Generated by Django 3.1.7 on 2021-04-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsaymodel',
            name='cowsay_type',
            field=models.CharField(choices=[('Default', 'Default'), ('Tux', 'Tux'), ('Dragon', 'Dragon'), ('Kitty', 'Kitty'), ('Skeleton', 'Skeleton')], default='Default', max_length=8),
        ),
    ]
