# Generated by Django 3.1.7 on 2021-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0002_cowsaymodel_cowsay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsaymodel',
            name='cowsay_type',
            field=models.CharField(choices=[('Default', 'Default'), ('Tux', 'Tux'), ('Dragon', 'Dragon'), ('Hello Kitty', 'Hello Kitty'), ('Skeleton', 'Skeleton')], default='Default', max_length=15),
        ),
    ]
